# Generated by Django 3.0.7 on 2020-06-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=200)),
                ('zipcode_type', models.CharField(blank=True, max_length=200, null=True)),
                ('major_city', models.CharField(blank=True, max_length=200, null=True)),
                ('post_office_city', models.CharField(blank=True, max_length=200, null=True)),
                ('common_city_list', models.BinaryField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lng', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=200, null=True)),
                ('radius_in_miles', models.TextField(blank=True, null=True)),
                ('area_code_list', models.BinaryField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('population_density', models.TextField(blank=True, null=True)),
                ('total_wage', models.IntegerField(blank=True, null=True)),
                ('land_area_in_sqmi', models.TextField(blank=True, null=True)),
                ('water_area_in_sqmi', models.TextField(blank=True, null=True)),
                ('housing_units', models.IntegerField(blank=True, null=True)),
                ('occupied_housing_units', models.IntegerField(blank=True, null=True)),
                ('median_home_value', models.IntegerField(blank=True, null=True)),
                ('median_household_income', models.IntegerField(blank=True, null=True)),
                ('bounds_west', models.TextField(blank=True, null=True)),
                ('bounds_east', models.TextField(blank=True, null=True)),
                ('bounds_north', models.TextField(blank=True, null=True)),
                ('bounds_south', models.TextField(blank=True, null=True)),
                ('polygon', models.BinaryField(blank=True, null=True)),
                ('population_by_year', models.BinaryField(blank=True, null=True)),
                ('population_by_age', models.BinaryField(blank=True, null=True)),
                ('population_by_gender', models.BinaryField(blank=True, null=True)),
                ('population_by_race', models.BinaryField(blank=True, null=True)),
                ('head_of_household_by_age', models.BinaryField(blank=True, null=True)),
                ('families_vs_singles', models.BinaryField(blank=True, null=True)),
                ('households_with_kids', models.BinaryField(blank=True, null=True)),
                ('children_by_age', models.BinaryField(blank=True, null=True)),
                ('housing_type', models.BinaryField(blank=True, null=True)),
                ('year_housing_was_built', models.BinaryField(blank=True, null=True)),
                ('housing_occupancy', models.BinaryField(blank=True, null=True)),
                ('vancancy_reason', models.BinaryField(blank=True, null=True)),
                ('owner_occupied_home_values', models.BinaryField(blank=True, null=True)),
                ('rental_properties_by_number_of_rooms', models.BinaryField(blank=True, null=True)),
                ('monthly_rent_including_utilities_studio_apt', models.BinaryField(blank=True, null=True)),
                ('monthly_rent_including_utilities_1_b', models.BinaryField(blank=True, null=True)),
                ('monthly_rent_including_utilities_2_b', models.BinaryField(blank=True, null=True)),
                ('monthly_rent_including_utilities_3plus_b', models.BinaryField(blank=True, null=True)),
                ('employment_status', models.BinaryField(blank=True, null=True)),
                ('average_household_income_over_time', models.BinaryField(blank=True, null=True)),
                ('household_income', models.BinaryField(blank=True, null=True)),
                ('annual_individual_earnings', models.BinaryField(blank=True, null=True)),
                ('sources_of_household_income_percent_of_households_receiving_income', models.BinaryField(blank=True, db_column='sources_of_household_income____percent_of_households_receiving_income', null=True)),
                ('sources_of_household_income_average_income_per_household_by_income_source', models.BinaryField(blank=True, db_column='sources_of_household_income____average_income_per_household_by_income_source', null=True)),
                ('household_investment_income_percent_of_households_receiving_investment_income', models.BinaryField(blank=True, db_column='household_investment_income____percent_of_households_receiving_investment_income', null=True)),
                ('household_investment_income_average_income_per_household_by_income_source', models.BinaryField(blank=True, db_column='household_investment_income____average_income_per_household_by_income_source', null=True)),
                ('household_retirement_income_percent_of_households_receiving_retirement_incom', models.BinaryField(blank=True, db_column='household_retirement_income____percent_of_households_receiving_retirement_incom', null=True)),
                ('household_retirement_income_average_income_per_household_by_income_source', models.BinaryField(blank=True, db_column='household_retirement_income____average_income_per_household_by_income_source', null=True)),
                ('source_of_earnings', models.BinaryField(blank=True, null=True)),
                ('means_of_transportation_to_work_for_workers_16_and_over', models.BinaryField(blank=True, null=True)),
                ('travel_time_to_work_in_minutes', models.BinaryField(blank=True, null=True)),
                ('educational_attainment_for_population_25_and_over', models.BinaryField(blank=True, null=True)),
                ('school_enrollment_age_3_to_17', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
