# Generated by Django 3.0.7 on 2020-06-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='annual_individual_earnings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='area_code_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='average_household_income_over_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='children_by_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='common_city_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='educational_attainment_for_population_25_and_over',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='employment_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='families_vs_singles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='head_of_household_by_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='household_income',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='household_investment_income_average_income_per_household_by_income_source',
            field=models.TextField(blank=True, db_column='household_investment_income____average_income_per_household_by_income_source', null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='household_investment_income_percent_of_households_receiving_investment_income',
            field=models.TextField(blank=True, db_column='household_investment_income____percent_of_households_receiving_investment_income', null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='household_retirement_income_average_income_per_household_by_income_source',
            field=models.TextField(blank=True, db_column='household_retirement_income____average_income_per_household_by_income_source', null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='household_retirement_income_percent_of_households_receiving_retirement_incom',
            field=models.TextField(blank=True, db_column='household_retirement_income____percent_of_households_receiving_retirement_incom', null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='households_with_kids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='housing_occupancy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='housing_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='means_of_transportation_to_work_for_workers_16_and_over',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='monthly_rent_including_utilities_1_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='monthly_rent_including_utilities_2_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='monthly_rent_including_utilities_3plus_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='monthly_rent_including_utilities_studio_apt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='owner_occupied_home_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='polygon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='population_by_age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='population_by_gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='population_by_race',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='population_by_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='rental_properties_by_number_of_rooms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='school_enrollment_age_3_to_17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='source_of_earnings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='sources_of_household_income_average_income_per_household_by_income_source',
            field=models.TextField(blank=True, db_column='sources_of_household_income____average_income_per_household_by_income_source', null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='sources_of_household_income_percent_of_households_receiving_income',
            field=models.TextField(blank=True, db_column='sources_of_household_income____percent_of_households_receiving_income', null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='travel_time_to_work_in_minutes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='vancancy_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='year_housing_was_built',
            field=models.TextField(blank=True, null=True),
        ),
    ]
